name: CI

on:
  push:
    paths:
      - 'src/**/*.ts'
      - 'src/**/*.tsx'
    
jobs:
    run-tests:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v5
        - uses: actions/setup-node@v5
        
        - run: cd autofin
        
        - run: npm i

        - run: npm run test
